services:
  - type: web
    name: one-api
    env: java
    plan: free
    branch: main
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: PORT
        value: 8080
